### ISSUE TITLE
For some reason, the jars built by `jrubyfx-jarify` on 9k for **a spefic ** repo do not run 

### ISSUE THREAD

**Issue by oreoshake** [jruby/jrubyfx#102]
Cross-post from https://github.com/jruby/jruby/issues/4000

For some reason, the jars built by `jrubyfx-jarify` for **[this](https://github.com/oreoshake/jrubyfx-9k-jar-problems)** repo do not run on jruby 9k (9.1.2.0) but run fine when generated by 1.7.x 1.7.21). I have built jars with 9k that ran fine, so I'm not sure what is different about the provided example repo.

I tried to trim the example down as much as possible while keeping in all of the (potentially bad) techniques we are using. I've never understood the ruby loadpath well at all, let alone how that might be different on jruby.

### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
  * `jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [darwin-x86_64]`
* Operating system and platform (e.g. `uname -a`)
  * `Darwin Neils-MacBook-Pro-4.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64`

Other relevant info you may wish to add:
* Installed or activated gems
  * https://github.com/oreoshake/jrubyfx-9k-jar-problems/blob/master/Gemfile.lock
* Application/framework version (e.g. Rails, Sinatra)
  * JrubyFX
* Environment variables

### Expected Behavior

The test application at https://github.com/oreoshake/jrubyfx-9k-jar-problems should build and run just fine. `$ bundle && rake && java -jar BrakemanPro.jar` should launch the app.

### Actual Behavior

builds and runs just fine under jruby 1.7.21, but fails under 9k:

```
$ bundle && rake && java -jar BrakemanPro.jar
Errno::ENOENT: No such file or directory - classpath:/Users/neilmatatall/workspace/jrubyfail/brakeman-pro/jar-bootstrap.rb
          realpath at org/jruby/RubyFile.java:810
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:11
             <top> at classpath:jar-bootstrap.rb:1
```

But if I unzip the jar and run the file directly, everything is happy:

```
$ mkdir tmp && cp BrakemanPro.jar tmp/ && cd tmp && unzip BrakemanPro.jar 
... accept the file overwrites ... 
$ ruby jar-bootstrap.rb
```

There's also a flag for compiling code and using that in the jar, but I ran into errors that I can  no longer reproduce so it's disabled by default.

**Comment by byteit101** [comment]
Not surprised. The way we build that jar is rather hacky. I have been rather busy unfortunately, and will likely be so for the near future, but if you aren't using the native packaging flag, you should be able to get other tools such as warbler to package it correctly.

**Comment by oreoshake** [comment]
@byteit101 thanks for the response. We aren't using the `--native` flag in the `jarify` command:

```
bundle exec jrubyfx-jarify . --main bin/brakeman_pro_jar.rb BrakemanPro.jar --include-jars --verbose --name "BrakemanPro"
```

We build the native apps via ant: https://github.com/oreoshake/jrubyfx-9k-jar-problems/blob/master/Rakefile#L7

There's some activity on the [cross-posted jruby issue](https://github.com/jruby/jruby/issues/4000) and it looks like something in jruby 1.7.22 is the cause of this difference in behavior.

**Comment by oreoshake** [comment]
This was fixed in https://github.com/jruby/jruby/issues/4000. There's some ongoing discussion in https://github.com/jruby/jrubyfx/issues/101.
