### ISSUE TITLE
JavaFX runtime not found

### ISSUE THREAD

**Issue by dangnlg2** [jruby/jrubyfx#109]
OS : OS X El Capitan
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
Latest version of jrubyfx

I am trying to launch a jrubyfx GUI from a Java application, but I am currently running into the following issue : 

"JavaFX runtime not found.  Please install Java 7u6 or newer or set environment variable JFX_DIR to the folder that contains jfxrt.jar"

I have set the environment variable to the correct path of the jfxrt.jar but it is still not working. Any help is greatly appreciated.

**Comment by byteit101** [comment]
Hmm interesting, java 102 must have moved the jars on osx. Could you please find the path that jfxrt.jar is actually at underneath your java home and send it to me?

**Comment by dangnlg2** [comment]
@byteit101  here is the path to my jar

/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/jfxrt.jar

I edited the path and the issue is now resolved. But I am running into an 'open_stream' error when I tried to launch the jar from a Java application. Could you resolve this? or should I create another issue?

**Comment by byteit101** [comment]
Hmm, ok that is odd, you shouldn't need to provide JFX_DIR for that. Is this the released version or from master?

**Comment by dangnlg2** [comment]
This is the released version, I have tried to run it off master as well. The main issue now is that I keep running into the 'open_stream' error, it cannot find my fxml file when I specify the `fxml_root` as :
 
`fxml_root File.dirname(__FILE__)`

I have tried hard coding the path to the fxml file, I then run into the following issue :

#<NoMethodError: undefined method `[]' for nil:NilClass>
/Applications/MagicDraw/plugins/csrr/csrr_gemjar.jar!/gems/jrubyfx-1.1.1-java/lib/jrubyfx/controller.rb:352:in `get_fxml_loader'

**Comment by byteit101** [comment]
JRubyFX 2.0 has been released. Your issue may have been fixed in 2.0. If your issue still applies to JRubyFX 2.0, please reopen this issue.
