### ISSUE TITLE
jrubyfx sensitive to number of spaces in fxml

### ISSUE THREAD

**Issue by natelljahns** [jruby/jrubyfx#111]
I am trying to use jrubyfx and fxml (generated by Gluon). I modified fxml to add an action :
<Button onAction="#start"...>

But, depending on the number of spaces between "Button" and "onAction", my application crashes...The required number is 2 blank spaces !

My settings :
    linux mint  3.13.0-37-generic
    jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [linux-x86_64]
    jrubyfx (1.2.0 java)
    jrubyfx-fxmlloader (0.4.1 java)

Hope this helps
Bye !
JCLL

==============
require 'jrubyfx'

fxml_root File.dirname(FILE)

class Test < JRubyFX::Application

def start(stage)
with(stage, title: 'test_1') do
fxml MyController
end
stage.show
end
end

class MyController
include JRubyFX::Controller
fxml 'test_1.fxml'

on :start do
@label_1.text="started"
end

on :stop do
@label_1.text="stopped"
end

end
Test.launch

**Comment by byteit101** [comment]
Hmm... that's odd. We use java standard xml parsing with SAX, so this is strange. 

However, I can't reproduce this on my end. Could you please paste your fxml file somewhere?

**Comment by natelljahns** [comment]
Yes, that was really really odd ! 
However, I've not been able to reproduce the bug this morning. I don't know what occurred.  Sorry.
I believe it's worth closing the ticket.
