### ISSUE TITLE
jrubyfx não encaminhando

### ISSUE THREAD

**Issue by Thieles** [jruby/jrubyfx#123]
Boa tarde,
Estou recebendo a seguinte exception
`Exception in thread "JavaFX Application Thread" org.jruby.exceptions.NameError: (NameError) no method 'setInt' for arguments (org.jruby.RubyFixnum,org.jruby.gen.RubyObject16) on Java::ComMysqlJdbc::JDBC42CallableStatement
  available overloads:
    (int,int)
    (int,int)
    (java.lang.String,int)
        at RUBY.block in on_read(/home/chezni/Documentos/vscode_project/center_of_control/lib/database/pessoa_fisica_dal.rb:25)
        at RUBY.block in on_read_pessoa_fisica(/home/chezni/Documentos/vscode_project/center_of_control/lib/database/database.rb:16)`, mas o erro não é verdadeiro pois o código foi testado separadamente e funciona perfeitamente.
O que eu consegui identificar foi que a JrubyFx não está fazendo o encaminhamento para o Jruby tratar e está lançando essa exception.

Podem me ajudar nesse bug?
Desde já agraceço.

**Comment by byteit101** [comment]
I don't understand the issue here, and the language barrier isn't helping. It looks like a JDBC issue? I don't see how this relates to JRubyFX. Could you provide more context (source, etc) if it is indeed an issue with JRubyFX?

**Comment by byteit101** [comment]
JRubyFX 2.0 has been released. Your issue may have been fixed in 2.0. If your issue still applies to JRubyFX 2.0, please reopen this issue.
