### ISSUE TITLE
Path to jfxrt.jar loading issue with 1.8.0_202-ea-b03

### ISSUE THREAD

**Issue by stergiom** [jruby/jrubyfx#125]
`require 'jrubyfx'` on `1.8.0_202-ea-b03` fails with:
```
JavaFX runtime not found.  Please install Java 7u6 or newer or set environment variable JFX_DIR to the folder that contains jfxrt.jar
If you have Java 7u6 or later, this is a bug. Please report to the issue tracker on github. Include your OS version, 32/64bit, and architecture (x86, ARM, PPC, etc)
```
..`jfxrt.jar` seems to be in the same place and I have had no trouble with `1.8.0_192`, I am getting around this issue with a pre-require `$LOAD_PATH << File.join(ENV_JAVA["sun.boot.library.path"], "/ext")` but unsure about whether something has changed and it now needs to be explicitly loaded somewhere around https://github.com/jruby/jrubyfx/blob/master/lib/jrubyfx/part_imports.rb#L25

Environment details:
```sh
jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 Java HotSpot(TM) 64-Bit Server VM 25.202-b03 on 1.8.0_202-ea-b03 +jit [darwin-x86_64]

#also
jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 OpenJDK 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [darwin-x86_64]
```

A possibly similar issue was seen at #82

**Comment by byteit101** [comment]
JRubyFX 2.0 has been released. Your issue may have been fixed in 2.0 If your issue still applies to JRubyFX 2.0, please reopen this issue.
