### ISSUE TITLE
get_fxml_loader seems to work differently when in jar

### ISSUE THREAD

**Issue by amiracam** [jruby/jrubyfx#74]
So I have managed to pack up app in a jar which then upon launching the jar I encounter this:

``` ruby
 fx.location =
      if JRubyFX::Application.in_jar?
      # If we are in a jar file, use the class loader to get the file from the jar (like java)
      # TODO: should just be able to use URLs
      JRuby.runtime.jruby_class_loader.get_resource File.join(root_dir, filename)
    else
      root_dir ||= fxml_root
      # If we are in the normal filesystem, create a file url path relative to relative_to or this file
      URL.new "file:#{File.join root_dir, filename}"
    end
```

the app upon launching ie. 

``` bash
  java -jar myjar.jar
```

crashes in the attempt to do the file join because <root_dir> is nil although `fxml_root` was specified in the app.

Launching the app works outside of the jar , where there's protection in place to assure that `root_dir` has `fxml_root` . 

From a quick glance it seems that `root_dir` should have? been picked up via "settings" but apparently its not. Have to go now, I'll spend more time on this tomorrow.

Here's the debug stack:

```
root dir : 
filename : amn_main_ui2.fxml
Exception running Application:
#<TypeError: can't convert nil into String>
org/jruby/RubyFile.java:1895:in `join'
org/jruby/RubyFile.java:826:in `join'
/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-1.1.0-java/lib/jrubyfx/controller.rb:341:in `get_fxml_loader'
/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-1.1.0-java/lib/jrubyfx/controller.rb:117:in `load_into'
./lib/amn_main_ui.rb:19:in `start'
/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-1.1.0-java/lib/jrubyfx/java_fx_impl.rb:125:in `launch_app_after_platform'
org/jruby/gen/InterfaceImpl1217949027.gen:13:in `run'
loading amn
```

**Comment by dangnlg2** [comment]
I am running into the same issue, I'm stuck with this error every time I try to launch my application

Exception in thread "JavaFX Application Thread" org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `open_stream' for nil:NilClass

my file structure looks like this :

plugin/source.rb (source code + controller)
plugin/CMT3.fxml (fxml file)

my fxml_root looks like this 'fxml_root File.dirname(__FILE__)'

I have tried everything and am still stuck on the 'open_stream' (NoMethodError). 

Any help would be greatly appreciated.

**Comment by dangnlg2** [comment]
@jjgh any insight?

**Comment by jjgh** [comment]
I am sorry @dangnlg2 I don't remember now, and I don't have time to go through this all again. Are you sure you are using latest warbler version? I hope someone else here can help you a bit more on this.
