### ISSUE TITLE
no jcreate for Java::JavafxGeometry::Insets

### ISSUE THREAD

**Issue by amiracam** [jruby/jrubyfx#76]
upon trying to load an fxml file from within a jar I have had to do explicit import statements for the various components referred to within the file. Not ideal but the approach has worked until i bumped into trying to do the same for Insets i.e.

java_import 'javafx.geometry.Insets'

note, the import did not crash but as fxmlloader processed the file it crashed as can be seen below in the debug stack. Note that the package that fxmlloader wants to operate on is: Java::JavafxGeometry as opposed to Java::Javafx::Geometry, perhaps this is just jrubyfx DSL but in any case it cannot construct the Java object.
# &lt;ArgumentError: no __jcreate! with arguments matching [] on object Java::JavafxGeometry::Insets>

/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/real_elts.rb:115:in `constructValue'
/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/value_elts.rb:62:in`processStartElement'
/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-fxmlloader-0.3-java/lib/jrubyfx-fxmlloader.rb:442:in `processStartElement'
/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-fxmlloader-0.3-java/lib/jrubyfx-fxmlloader.rb:354:in`load'
/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-1.1.0-java/lib/jrubyfx/controller.rb:117:in `load_into'
./lib/amn_main_ui.rb:19:in`start'
/Users/charles/.rvm/gems/jruby-1.7.6/gems/jrubyfx-1.1.0-java/lib/jrubyfx/java_fx_impl.rb:125:in `launch_app_after_platform'
org/jruby/gen/InterfaceImpl865441117.gen:13:in`run'

**Comment by byteit101** [comment]
JRubyFX 2.0 has been released. Your issue may have been fixed in 2.0. If your issue still applies to JRubyFX 2.0, please reopen this issue.
