### ISSUE TITLE
NoMethodError: undefined method `int' for RubyWrapperBeanAdapter:Class

### ISSUE THREAD

**Issue by joshuamzm** [jruby/jrubyfx#90]
I got this problem while trying to run a jrubyfx-generated Dummy.fxml... 

Code here: https://gist.github.com/jomendoz/5a1ef9dd0fb11519afe9

And error here: https://gist.github.com/jomendoz/c06268416be82148c8e9

Any clue?

**Comment by jomendoz** [comment]
Specs:
JRuby 1.7.18
JRubyFX: github 892af575c876cf7c2152ee365736c2a724dc4445 > 1.1.1
OpenJDK: jdk8-openjdk 8.u25-2
SceneBuilder: 2.0.1

**Comment by jomendoz** [comment]
I think I caught the nail in the rye. It seems everything is ok but TableView's property, "Column Resize Policy". Its default goes for "unconstrained-resize" but if I use "constrained-resize", theoretically, all columns resize evenly to match parent's width. But when I use this .fxml in JRubyFX, the error that I previously shared appears again.

Diffing the two .fxml shows  the following:
7a8
> 
66a68,70
>          <columnResizePolicy>
>             <TableView fx:constant="CONSTRAINED_RESIZE_POLICY" />
>          </columnResizePolicy>

So my guess is that JRubyFX::Controller::fxml doesn't deal well with that constant. But no time for further research.

**Comment by oreoshake** [comment]
fwiw I've had luck setting this in ruby land (I have no idea if the long constant can be shortened):

`@some_table.column_resize_policy = javafx::scene::control::TableView::CONSTRAINED_RESIZE_POLICY`

**Comment by byteit101** [comment]
Fix dependent upon https://github.com/jruby/jruby/issues/3366

**Comment by byteit101** [comment]
JRubyFX 2.0 has been released. Your issue may have been fixed in 2.0. If your issue still applies to JRubyFX 2.0, please reopen this issue.
