### ISSUE TITLE
Requiring jrubyfx causes rspec to hang

### ISSUE THREAD

**Issue by lexun** [jruby/jrubyfx#91]
I'm using `ruby 1.9.3` on `jruby 1.7.18` with `jrubyfx 1.1.1` and `rspec 3.1.0`

I just started a project with barely more than hello world. I noticed that as soon as I added this:
```ruby
require 'jrubyfx'
```
My tests would finish as usual, but rspec would not exit and the java process would continue running.

I tried this on both my mac and linux boxes and got the same results. I'm not sure how to troubleshoot further at this point. Any ideas?

Thanks!

**Comment by byteit101** [comment]
Yes, you need to exit the toolkit. see the app compiler and jrubyfx rake tasks (in lib) to see how we do it in rake

**Comment by lexun** [comment]
Cool, thanks for the quick reply! All it took was:

```ruby
RSpec.configure do |config|
  config.after(:suite) do
    JavaFXImpl::PlatformImpl.tkExit
  end
end
```
