### ISSUE TITLE
Controller stage not right when created with fxml

### ISSUE THREAD

**Issue by lexun** [jruby/jrubyfx#92]
Whenever I create a new stage and delegate to a new controller with the fxml= method, I'd expect that the newly created stage would be passed to the new controller as it's stage. This doesn't seem to be the case.

I'll use a global to illustrate the issue:

```ruby
class Application < JRubyFX::Application
  fxml_root 'lib/gui/fxml'

  def start(stage)
    $stage = stage

    with(stage) do
      fxml MainController
      show
    end
  end
end

class MainController
  include JRubyFX::Controller
  fxml 'main.fxml'

  def some_action
    # returns false
    $stage == self.stage

    # returns NaN
    self.stage.x

    # returns 556.0
    $stage.x
  end
end

```

Is this the intended behavior? Am I going about this wrong?

**Comment by byteit101** [comment]
`@stage`, not `self.stage`

self.stage is a dsl call to create a new stage

**Comment by lexun** [comment]
Of course, that makes sense. Thanks for the help.
