### ISSUE TITLE
gem missing

### ISSUE THREAD

**Issue by kuerbi** [jruby/jrubyfx#96]
gem missing

gem install jrubyfx 

ERROR:  Could not find a valid gem 'jrubyfx' (>= 0) in any repository

**Comment by byteit101** [comment]
CNR. I just installed it successfully via gem and it shows up at https://rubygems.org/gems/jrubyfx/versions/1.1.1-java  

Are you using jruby gem or mri gem? Jruby gem can be accessed via `jruby -S gem` if you don't have the symlinks set up a-la rvm

**Comment by kuerbi** [comment]
thank you :-). you were right i have used mri gem. it works with jruby -S gem
